// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20uboRZX3_Oho0BaMRrAlaiTr2Y45xQI',
    appId: '1:998035074820:web:6c2db1da6a4de897f36a51',
    messagingSenderId: '998035074820',
    projectId: 'food-prep-app-87f66',
    authDomain: 'food-prep-app-87f66.firebaseapp.com',
    storageBucket: 'food-prep-app-87f66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_3fn5lM4nGOXSbooEzyBif04OwgmpUB4',
    appId: '1:998035074820:android:1ac603753a007d13f36a51',
    messagingSenderId: '998035074820',
    projectId: 'food-prep-app-87f66',
    storageBucket: 'food-prep-app-87f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcpzLqrtU-JN-gg_-LOpUkle4xfsfC0k',
    appId: '1:998035074820:ios:7b82342a8a43c223f36a51',
    messagingSenderId: '998035074820',
    projectId: 'food-prep-app-87f66',
    storageBucket: 'food-prep-app-87f66.firebasestorage.app',
    iosBundleId: 'com.fghilmany.mealmind.app',
  );
}
